repeat task.wait()
until game:IsLoaded()
game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-360.825226, 21340.6465, -598.533325)
setfpscap(25)
_G.settingsTable = {
    autobubble = true;
    autowheel = true;
    autoegg = true;
}



local replicatedStorage = game:GetService("ReplicatedStorage")


local eggs = replicatedStorage["Game Objects"].Eggs["Spawn World"]

local eggList = {}
for _, egg in pairs(eggs:GetChildren()) do
     table.insert(eggList, egg.Name)
end


    

local library = loadstring(game:HttpGet(('https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wall%20v3')))()

local w = library:CreateWindow("BGC")

local AF = w:CreateFolder("Auto Farm")

local E = w:CreateFolder("Eggs")

AF:Toggle("Auto Bubble",function(bool)
    _G.settingsTable.autobubble = bool
    saveSettings()
end)


spawn(function()
    while wait() do
        if _G.settingsTable.autobubble then
 local args = {
    [1] = {
        [1] = {
            [1] = false
        },
        [2] = {
            [1] = 2
        }
    }
}

game:GetService("ReplicatedStorage").Remotes:FindFirstChild("blow bubble"):FireServer(unpack(args))

        end
    end
end)


AF:Toggle("Auto Wheel",function(bool)
    _G.settingsTable.autowheel = bool
    saveSettings()
end)


spawn(function()
    while Wheel and task.wait(14460) do
        if _G.settingsTable.autowheel then
    
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = {
        [1] = {
            [1] = false
        },
        [2] = {
            [1] = 2
        }
    }
}

game:GetService("ReplicatedStorage").Remotes:FindFirstChild("free wheel spin"):InvokeServer(unpack(args))

        end
    end
end)

E:Toggle("Open x3",function(bool)
    _G.settingsTable.autoegg = bool
    saveSettings()
end)


spawn(function()
    while wait() do
        if _G.settingsTable.autoegg then
         
            wait(1)
 -- Script generated by SimpleSpy - credits to exx#9394

local args = {
            [1] = {
                [1] = {
                    [1] = "Galaxy Egg",
                    [2] = true
                },
                [2] = {
                    [1] = false,
                    [2] = false
                }
                }
            }
            game:GetService("ReplicatedStorage").Remotes:FindFirstChild("buy egg"):InvokeServer(unpack(args))
        
        end
    end
end)

E:Dropdown("Eggs",eggList,true,function(mob)
    print(mob)
    saveSettings()
end)


